name: 2d3d
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy<2
  - scipy
  - pip
  - open3d
  - opencv
  - tqdm
  - zarr
  - dask
  - dask-image
  - tqdm
  - pillow
  - pip:
    - fastmorph

